-- EXCLUINDO uma CONSTRAINT
ALTERAR TABLE ALUNO APAGANDO CONSTRAINT xxx
ALTER TABLE ALUNO DROP CONSTRAINT SYS_C007149
OU
-- EXCLUINDO uma CONSTRAINT do tipo NOT NULL (só é possível assim para NOT NULL)
ALTER TABLE ALUNO MODIFY (NOME VARCHAR(50) NULL)

-- EXCLUINDO uma CONSTRAINT
ALTER TABLE ALUNO DROP CONSTRAINT SYS_C007151
OU
-- EXCLUINDO uma CONSTRAINT do tipo PRIMARY KEY (só é possível assim para PRIMARY KEY)
ALTER TABLE ALUNO DROP PRIMARY KEY

-- RENOMEANDO uma TABELA
ALTERAR TABELA ALUNO RENOMEANDO PARA ALUNOS
ALTER   TABLE  ALUNO RENAME      TO  ALUNOS 
OU
-- RENOMEANDO uma tabela sem precisar usar o ALTER TABLE
RENAME ALUNO TO ALUNOS

-- RENOMEANDO uma coluna de uma tabela
ALTERAR TABELA ALUNO RENOMEANDO COLUNA ENDER PARA ENDERECO
ALTER   TABLE  ALUNO RENAME     COLUMN ENDER  TO  ENDERECO

-- EXCLUINDO uma coluna de uma tabela
ALTERAR TABELA ALUNO APAGANDO COLUNA OBSERV
ALTER   TABLE  ALUNO DROP     COLUMN OBSERV

-- ADICIONANDO uma nova coluna numa tabela
ALTER TABLE ALUNO ADD OBSERV VARCHAR(50)

-- ADICIONANDO novas colunas com e sem restrições
ALTER TABLE ALUNO
ADD
(
CPF VARCHAR(15) UNIQUE,
RG VARCHAR(14)		  
)

-- ADICIONAND0 uma CONSTRAINT de NOT NULL numa coluna já existente 
-- (NOT NULL sempre será pelo MODIFY, nunca pelo ADD CONSTRAINT)
ALTER TABLE ALUNO
MODIFY
(
CPF CONSTRAINT ALUNO_CPF_NN NOT NULL
)
OU
ALTER TABLE ALUNO
MODIFY
(
CPF VARCHAR(15) CONSTRAINT ALUNO_CPF_NN NOT NULL
)

-- MODIFICANDO tamanho de uma coluna já existente na tabela
ALTERAR TABELA ALUNO MODIFICANDO ENDER VARCHAR(80)
ALTER   TABLE  ALUNO 	MODIFY	 ENDER VARCHAR(80)

-- igual a linha anterior, apenas escrito em várias linhas
ALTER TABLE ALUNO
MODIFY
(
ENDER VARCHAR(80)
)

-- ADICIONANDO uma CONSTRAINT numa coluna já existente na tabela
ALTERAR TABELA ALUNO ADICIONANDO CONSTRAINT UNIQUE
ALTER   TABLE  ALUNO     ADD	 CONSTRAINT ALUNO_RG_UU UNIQUE (RG)

-- igual a linha anterior, apenas escrito em várias linhas
ALTER TABLE ALUNO
ADD
(
CONSTRAINT ALUNO_RG_UU UNIQUE(RG)	  
)
ou
-- sem dar nome a constraint
ALTER TABLE ALUNO
ADD
(
UNIQUE(RG)	  
)






