SELECT 		-- 	LISTA DE CAMPOS
FROM 		--	NOME DA TABELA
WHERE		-- 	FILTRA LINHAS NA TABELA
ORDER BY	--	ORDENA/CLASSIFICA AS LINHAS RESULTANTES

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 30
--OU
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN (10, 30)

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO <> 10 AND DEPTNO <> 30
--OU
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO NOT IN (10, 30)

SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE SAL >= 1500 AND SAL <= 2500
--OU
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE SAL BETWEEN 1500 AND 2500

SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE SAL < 1500 OR SAL > 2500
--OU
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE SAL NOT BETWEEN 1500 AND 2500

SELECT *
FROM ALUNO
WHERE NOME  LIKE  'LAURA%'

SELECT *
FROM ALUNO
WHERE NOME  LIKE  '%LAURA%'

SELECT *
FROM ALUNO
WHERE NOME  LIKE  '%LAURA'

SELECT *
FROM EMP
WHERE ENAME LIKE 'A%'

SELECT *
FROM EMP
WHERE ENAME LIKE '%A'

SELECT *
FROM EMP
WHERE ENAME LIKE '%A%'

SELECT *
FROM EMP
WHERE ENAME LIKE '%A%' OR JOB = 'SALESMAN'

SELECT *
FROM EMP
WHERE ENAME LIKE '%A%' AND JOB = 'SALESMAN'

SELECT *
FROM EMP
WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S'

SELECT *
FROM EMP
WHERE ENAME LIKE '%A%' AND ENAME LIKE '%S'

SELECT *
FROM ALUNO
WHERE NOME = '___ LUCIA%'

SELECT *
FROM EMP
WHERE JOB LIKE '__E%'

