INSERT INTO NOMETAB
(LISTA DE CAMPOS) -- OPCIONAL
VALUES
(LISTA DE VALORES)

--LISTA 2
INSERT INTO INSTRUTOR
(IDINST, NOME, TELEFONE, DTADM, SALARIO) -- OPCIONAL
VALUES
(1, 'JOSÉ MARINHO',9999-1234, SYSDATE, 2000,00)

--OU
INSERT INTO INSTRUTOR
(IDINST, NOME, TELEFONE, DTADM, SALARIO) -- OPCIONAL
VALUES
(1, 'JOSÉ MARINHO',9999-1234, '26/09/22',2000)

INSERT INTO INSTRUTOR
VALUES
(2, 'EULER SOARES', '4343-2000', '26/09/22', 1850.18)

--LISTA 1

INSERT INTO FILME
(CODFILME, TITULO, CODCATEG)
VALUES
(1, 'SAI PRA LÁ', NULL)

-- OU
INSERT INTO FILME
(CODFILME, TITULO)
VALUES
(1, 'SAI PRA LÁ')

INSERT INTO CATEGORIA
(CODCATEG, DESCRICAO)
VALUES
(1, 'COMÉDIA')

INSERT INTO CATEGORIA
(CODCATEG, DESCRICAO)
VALUES
(2, 'DRAMA')

-- UTILIZANDO PARÂMETRO (&)
INSERT INTO CATEGORIA
(CODCATEG, DESCRICAO)
VALUES
(&CODIGO, '&DESCRICAO')

--COMANDO UPDATE
UPDATE NOMETAB
SET
CAMPO = NOVO_VALOR
WHERE CONDICIONAL -- FILTRAR LINHAS PARA FAZER O QUE O COMANDO DETERMINA

-- TODAS AS LINHAS DA TABELA SERÃO ALTERADAS
UPDATE EMP
SET
SAL = 3200

-- APENAS AS LINHAS QUE ATENDEM A CONDIÇÃO DA CLÁUSULA WHERE SERÃO ALTERADAS
UPDATE EMP
SET
SAL = 3200
WHERE EMPNO = 7902

UPDATE EMP
SET
SAL = 3200
WHERE SAL < 2500 AND DEPTNO = 10

-- COMANDO DELETE
DELETE FROM NOMETAB WHERE CONDICIONAL

-- TODAS AS LINHAS DA TABELA EMP SERÃO ELIMINADAS
DELETE FROM EMP

-- APENAS AS LINHAS QUE ATENDEM A CONDIÇÃO DA CLÁUSULA WHERE SERÃO ELIMINADAS
DELETE FROM EMP
WHERE SAL > 1500 AND SAL <= 2000




















